kind: Secret
apiVersion: v1
metadata:
  name: extra-sistem-odoo-generic-webhook-secret
  namespace: odoo
  uid: 875946c9-9ad7-4a6c-938a-c093d1876781
  resourceVersion: '36065906'
  creationTimestamp: '2025-01-15T19:42:38Z'
  labels:
    app: extra-sistem-odoo
    app.kubernetes.io/component: extra-sistem-odoo
    app.kubernetes.io/instance: extra-sistem-odoo
    app.kubernetes.io/name: extra-sistem-odoo
    app.kubernetes.io/part-of: extra-sistem-odoo-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 20-ubi8
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-01-15T19:42:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:WebHookSecretKey': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:type': {}
data:
  WebHookSecretKey: ZTRkNTEyZWQwYzNhZTA3MA==
type: Opaque
